---
apiVersion: v1
kind: Namespace
metadata:
  name: n8n
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.35
          command: ['sh', '-c', 'chown -R 1000:1000 /home/node/.n8n']
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
        - name: install-npm-packages
          image: docker.n8n.io/n8nio/n8n:1.106.2
          command:
            - sh
            - -c
            - |
              mkdir -p /home/node/.n8n/node_modules
              cd /home/node/.n8n
              npm init -y
              npm install @actual-app/api
              chown -R 1000:1000 /home/node/.n8n
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:1.106.2
          ports:
            - containerPort: 5678
              protocol: TCP
          env:
            - name: TZ
              value: 'Europe/London'
            - name: NODE_FUNCTION_ALLOW_BUILTIN
              value: '*'
            - name: NODE_FUNCTION_ALLOW_EXTERNAL
              value: '*'
            - name: N8N_PROTOCOL
              value: https
            - name: WEBHOOK_URL
              value: https://n8n.dloez.dev
            - name: N8N_HOST
              value: n8n.dloez.dev
            - name: N8N_PORT
              value: '5678'
            - name: NODE_PATH
              value: '/home/node/.n8n/node_modules'
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
  labels:
    app: n8n
spec:
  type: ClusterIP
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    app: n8n
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-cert
  namespace: n8n
spec:
  secretName: n8n-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - n8n.dloez.dev
  privateKey:
    rotationPolicy: Always
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: n8n-gateway
  namespace: n8n
spec:
  gatewayClassName: traefik
  listeners:
    - name: websecure
      port: 8443
      protocol: HTTPS
      hostname: n8n.dloez.dev
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: n8n-tls
    - name: web
      port: 8000
      protocol: HTTP
      hostname: n8n.dloez.dev
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-https-redirect
  namespace: n8n
spec:
  parentRefs:
    - name: n8n-gateway
      sectionName: web
  hostnames:
    - n8n.dloez.dev
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-route
  namespace: n8n
spec:
  parentRefs:
    - name: n8n-gateway
      sectionName: websecure
  hostnames:
    - n8n.dloez.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: n8n-service
          port: 5678
