---
apiVersion: v1
kind: Namespace
metadata:
  name: tandoor
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-secret-key
  namespace: tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: tandoor/secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-postgres-password
  namespace: tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: tandoor/postgres-password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-postgres-data
  namespace: tandoor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-mediafiles
  namespace: tandoor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-staticfiles
  namespace: tandoor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandoor-postgres
  namespace: tandoor
  labels:
    app: tandoor-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tandoor-postgres
  template:
    metadata:
      labels:
        app: tandoor-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: tandoor
            - name: POSTGRES_DB
              value: tandoor
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-postgres-password
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - tandoor
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - tandoor
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: tandoor-postgres-data
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tandoor-postgres
  namespace: tandoor
  labels:
    app: tandoor-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: tandoor-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandoor
  namespace: tandoor
  labels:
    app: tandoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tandoor
  template:
    metadata:
      labels:
        app: tandoor
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /opt/recipes/mediafiles
              chown -R 1000:1000 /opt/recipes/staticfiles
          volumeMounts:
            - name: mediafiles
              mountPath: /opt/recipes/mediafiles
            - name: staticfiles
              mountPath: /opt/recipes/staticfiles
      containers:
        - name: tandoor
          image: vabene1111/recipes:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor-secret-key
                  key: secret-key
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: tandoor-postgres
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USER
              value: tandoor
            - name: POSTGRES_DB
              value: tandoor
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-postgres-password
                  key: postgres-password
          volumeMounts:
            - name: mediafiles
              mountPath: /opt/recipes/mediafiles
            - name: staticfiles
              mountPath: /opt/recipes/staticfiles
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
      volumes:
        - name: mediafiles
          persistentVolumeClaim:
            claimName: tandoor-mediafiles
        - name: staticfiles
          persistentVolumeClaim:
            claimName: tandoor-staticfiles
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tandoor-web
  namespace: tandoor
  labels:
    app: tandoor
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: tandoor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tandoor-cert
  namespace: tandoor
spec:
  secretName: tandoor-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - tandoor.dloez.dev
  privateKey:
    rotationPolicy: Always
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tandoor-gateway
  namespace: tandoor
spec:
  gatewayClassName: traefik
  listeners:
    - name: websecure
      port: 8443
      protocol: HTTPS
      hostname: tandoor.dloez.dev
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tandoor-tls
    - name: web
      port: 8000
      protocol: HTTP
      hostname: tandoor.dloez.dev
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tandoor-https-redirect
  namespace: tandoor
spec:
  parentRefs:
    - name: tandoor-gateway
      sectionName: web
  hostnames:
    - tandoor.dloez.dev
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tandoor-route
  namespace: tandoor
spec:
  parentRefs:
    - name: tandoor-gateway
      sectionName: websecure
  hostnames:
    - tandoor.dloez.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: tandoor-web
          port: 80
