apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: basic
  namespace: metallb
spec:
  addresses:
    - 192.168.1.19/32
    - 192.168.1.18/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: basic
  namespace: metallb
spec:
  ipAddressPools:
    - basic 
