k3s_cluster:
  children:
    server:
      hosts:
        192.168.1.10:
    agent:
      hosts:
        192.168.1.11:
  vars:
    k3s_version: v1.33.0+k3s1
    extra_server_args: "--disable servicelb --disable traefik"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
# setup_nodes:
#   hosts:
#     192.168.1.139:
#       static_ip: 192.168.1.10
#       hostname: server1.tom.home
#     192.168.1.140:
#       static_ip: 192.168.1.11
#       hostname: agent2.tom.home
