---
- name: Setup and configure nodes
  hosts: setup_nodes
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Set hostname
      hostname:
        name: "{{ hostname }}"

    - name: Configure static IP
      template:
        src: netplan.j2
        dest: /etc/netplan/01-netcfg.yaml
        mode: '0644'
      notify: apply_netplan

  handlers:
    - name: apply_netplan
      command: netplan apply 