---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: 0.17.0
  interval: 1m0s
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password
  namespace: external-secrets
spec:
  provider:
    onepasswordSDK:
      vault: K8s - Tom
      auth:
        serviceAccountSecretRef:
          name: 1password-service-token-tom
          key: token
          namespace: external-secrets
      integrationInfo:
        name: integration-info
        version: v1
