---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: address
      remoteRef:
        key: Discord webhook/password
