machine:
  install:
    disk: /dev/nvme0n1
  network:
    interfaces:
      - interface: end0
        dhcp: false
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
    nameservers:
      - 8.8.8.8
      - 8.8.4.4
