name: Flux auto image update
on:
  create:
jobs:
  pull-request:
    runs-on: ubuntu-latest
    environment: Tom
    if: |
      github.event.ref_type == 'branch' &&
      startsWith(github.event.ref, 'image-automation-')
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.FLUX_GITHUB_TOKEN }} # Required as a PR created by secrets.GITHUB_TOKEN would not trigger other workflows
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "Branch name: $branch_name"

          # Format: image-automation-CLUSTERNAME-APPNAME
          if [[ "$branch_name" =~ ^image-automation-([^-]+)-(.+)$ ]]; then
            cluster_name="${BASH_REMATCH[1]}"
            app_name="${BASH_REMATCH[2]}"
            cluster_name_upper=$(echo "$cluster_name" | tr '[:lower:]' '[:upper:]')
            app_name_title=$(echo "$app_name" | sed 's/\b\w/\U&/g')
            pr_title="($cluster_name_upper) Upgrade $app_name_title"
            echo "PR Title: $pr_title"
          else
            pr_title="Pulling ${branch_name} into main"
            echo "Using fallback title: $pr_title"
          fi

          # Create PR body
          pr_body="🤖 **Automated Image Update**

          This PR was automatically created by the Flux Image Automation workflow to update container images to their latest versions.

          📋 **What changed:**
          - Updated container image tags for the applications in this cluster

          🔄 **Automation Details:**
          - Generated by: Flux Image Automation Controller
          - Documentation: https://fluxcd.io/flux/guides/image-update/

          ⚠️ **Please review** the changes before merging to ensure compatibility."

          gh pr create \
            --repo=${GITHUB_REPO} \
            --head=${branch_name} \
            --base=main \
            --title="$pr_title" \
            --body="$pr_body" \
            --reviewer=dloez \
            --assignee=dloez
