name: (Flux) Auto image update
on:
 create:
jobs:
  pull-request:
    runs-on: ubuntu-latest
    if: |
      github.event.ref_type == 'branch' &&
      startsWith(github.event.ref, 'image-automation-')      
    permissions:
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        gh pr create \
          --repo=${GITHUB_REPO} \
          --head=${GITHUB_REF#refs/heads/} \
          --base=main \
          --title="Pulling ${GITHUB_REF} into main" \
          --body=":crown: *An automated PR*" \
          --reviewer=dloez
