name: Lint files
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main
jobs:
  fix-k8s-yaml-markers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Fix YAML document markers
        run: |
          # Get changed YAML files in the PR
          changed_files=$(git diff --name-only origin/main...HEAD | grep -E '\.(yaml|yml)$' | grep '^homelab/' || true)
          
          if [ -z "$changed_files" ]; then
            echo "No YAML files changed in homelab directory"
            exit 0
          fi
          
          echo "Changed YAML files:"
          echo "$changed_files"
          
          chmod +x scripts/add-yaml-markers.sh
          ./scripts/add-yaml-markers.sh $changed_files
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add homelab/
            git commit -m "add yaml document start markers"
            git push
            echo "Added YAML document markers and pushed changes"
          else
            echo "No changes needed"
          fi
